import 'package:flutter/material.dart';

class Strings {
  const Strings(this.code);
  final String code;
  static Strings of(BuildContext context) => Strings(Localizations.localeOf(context).languageCode);
  String t(String key) => _values[key]?[switch (code) {'az' => 1, 'tr' => 2, _ => 0}] ?? key;
  static const _values = <String, List<String>>{
    'tagline': ['Good people. Great conversations.', 'Yeni insanlar. Gözəl söhbətlər.', 'Yeni insanlar. Güzel sohbetler.'],
    'welcomeBody': ['Find your people, share your world, and make a little room for fun.', 'Dostlarını tap, dünyanı paylaş və əyləncəyə qoşul.', 'Arkadaşlarını bul, dünyanı paylaş ve eğlenceye katıl.'],
    'join': ['Create account', 'Hesab yarat', 'Hesap oluştur'],
    'login': ['Sign in', 'Daxil ol', 'Giriş yap'],
    'preview': ['Explore preview', 'Sınaq rejiminə bax', 'Ön izlemeyi keşfet'],
    'previewBanner': ['PREVIEW · Sample people, local messages & test coins', 'SINAQ · Nümunə profillər, lokal mesajlar və test coinləri', 'ÖN İZLEME · Örnek kişiler, yerel mesajlar ve test coinleri'],
    'setup': ['Account registration is opening soon. Explore the preview today.', 'Qeydiyyat tezliklə açılacaq. İndi sınaq rejiminə bax.', 'Kayıt yakında açılıyor. Şimdi ön izlemeyi keşfet.'],
    'discover': ['Discover', 'Kəşf et', 'Keşfet'],
    'rooms': ['Hangouts', 'Otaqlar', 'Odalar'],
    'play': ['Play', 'Oyna', 'Oyna'],
    'messages': ['Messages', 'Mesajlar', 'Mesajlar'],
    'profile': ['Profile', 'Profil', 'Profil'],
    'wallet': ['Wallet', 'Cüzdan', 'Cüzdan'],
    'language': ['Language', 'Dil', 'Dil'],
    'email': ['Email', 'E-poçt', 'E-posta'],
    'password': ['Password', 'Şifrə', 'Şifre'],
    'name': ['Display name', 'Görünən ad', 'Görünen ad'],
    'country': ['Country', 'Ölkə', 'Ülke'],
    'birthday': ['Date of birth', 'Doğum tarixi', 'Doğum tarihi'],
    'adult': ['I am 18+ and accept the community rules.', '18 yaşım tamamdır və icma qaydalarını qəbul edirəm.', '18 yaşından büyüğüm ve topluluk kurallarını kabul ediyorum.'],
    'rules': ['Community rules', 'İcma qaydaları', 'Topluluk kuralları'],
    'rulesBody': ['Adults only. Be respectful. No harassment, hate, sexual exploitation, scams or illegal content. Report harmful behavior and block unwanted contact. Coins are virtual items, not cash or gambling chips. Never share passwords or payment details in chat.', 'Yalnız böyüklər üçün. Hörmətli ol. Təqib, nifrət, cinsi istismar, dələduzluq və qanunsuz məzmun qadağandır. Zərərli davranışı şikayət et və istəmədiyin əlaqəni blokla. Coin virtual əşyadır, pul və ya qumar fişkası deyil. Söhbətdə şifrə və ödəniş məlumatlarını paylaşma.', 'Yalnızca yetişkinler. Saygılı ol. Taciz, nefret, cinsel istismar, dolandırıcılık ve yasa dışı içerik yasaktır. Zararlı davranışları bildir ve istenmeyen kişileri engelle. Coin sanal bir üründür, nakit veya kumar fişi değildir. Sohbette şifre veya ödeme bilgisi paylaşma.'],
    'validation': ['Check your details: name 2–40 characters, valid email, password at least 10 characters, country and an adult date of birth.', 'Məlumatları yoxla: ad 2–40 simvol, düzgün e-poçt, ən az 10 simvolluq şifrə, ölkə və 18+ doğum tarixi.', 'Bilgileri kontrol et: ad 2–40 karakter, geçerli e-posta, en az 10 karakterli şifre, ülke ve 18+ doğum tarihi.'],
    'verify': ['Check your email to confirm your account, then sign in.', 'Hesabı təsdiqləmək üçün e-poçtunu yoxla, sonra daxil ol.', 'Hesabını doğrulamak için e-postanı kontrol et, ardından giriş yap.'],
    'error': ['Something went wrong. Please try again.', 'Xəta baş verdi. Yenidən yoxla.', 'Bir sorun oluştu. Tekrar dene.'],
    'authError': ['Unable to sign in. Check your details and email confirmation.', 'Giriş alınmadı. Məlumatları və e-poçt təsdiqini yoxla.', 'Giriş yapılamadı. Bilgilerini ve e-posta doğrulamasını kontrol et.'],
    'signupError': ['Could not create the account. Check your details or try signing in.', 'Hesab yaradıla bilmədi. Məlumatları yoxla və ya giriş etməyi sına.', 'Hesap oluşturulamadı. Bilgilerini kontrol et veya giriş yapmayı dene.'],
    'retry': ['Try again', 'Yenidən yoxla', 'Tekrar dene'],
    'search': ['Search people or countries', 'Ad və ya ölkə axtar', 'Kişi veya ülke ara'],
    'all': ['All', 'Hamısı', 'Tümü'],
    'discoverTitle': ['Your next hello starts here.', 'Növbəti salamın buradan başlayır.', 'Bir sonraki merhaban burada başlıyor.'],
    'discoverBody': ['Different places. Shared interests. A world of possibilities.', 'Fərqli ölkələr. Ortaq maraqlar. Yeni tanışlıqlar.', 'Farklı ülkeler. Ortak ilgi alanları. Yeni tanışmalar.'],
    'people': ['Meet the community', 'İcma ilə tanış ol', 'Toplulukla tanış'],
    'emptyPeople': ['No people found. Try another search or invite a friend.', 'İstifadəçi tapılmadı. Başqa axtarış et və ya dostunu dəvət et.', 'Kimse bulunamadı. Başka arama yap veya bir arkadaşını davet et.'],
    'chat': ['Say hello', 'Salam yaz', 'Merhaba de'],
    'gift': ['Send a gift', 'Hədiyyə göndər', 'Hediye gönder'],
    'report': ['Report', 'Şikayət et', 'Bildir'],
    'block': ['Block user', 'İstifadəçini blokla', 'Kullanıcıyı engelle'],
    'unblock': ['Unblock', 'Bloku aç', 'Engeli kaldır'],
    'blocked': ['Blocked accounts', 'Bloklanmış hesablar', 'Engellenen hesaplar'],
    'reportSent': ['Report received. Thank you for helping the community.', 'Şikayət qəbul edildi. İcmaya köməyin üçün sağ ol.', 'Bildirim alındı. Topluluğa yardımın için teşekkürler.'],
    'previewReport': ['Preview only: no report was sent to a moderator.', 'Sınaq rejimi: moderatora şikayət göndərilmədi.', 'Ön izleme: moderatöre bildirim gönderilmedi.'],
    'Harassment': ['Harassment', 'Təqib', 'Taciz'],
    'Spam': ['Spam', 'Spam', 'Spam'],
    'Inappropriate content': ['Inappropriate content', 'Uyğunsuz məzmun', 'Uygunsuz içerik'],
    'Underage': ['Underage', 'Yetkinlik yaşına çatmayan', 'Reşit olmayan'],
    'Other': ['Other', 'Digər', 'Diğer'],
    'cancel': ['Cancel', 'Ləğv et', 'İptal'],
    'send': ['Send', 'Göndər', 'Gönder'],
    'write': ['Write a message…', 'Mesaj yaz…', 'Mesaj yaz…'],
    'emptyChat': ['A good conversation starts with hello.', 'Gözəl söhbət salamla başlayır.', 'Güzel bir sohbet merhaba ile başlar.'],
    'emptyMessages': ['Your conversations will appear here. Find someone in Discover to get started.', 'Söhbətlərin burada görünəcək. Başlamaq üçün Kəşf et bölməsindən birini seç.', 'Sohbetlerin burada görünecek. Başlamak için Keşfet bölümünden birini seç.'],
    'messageError': ['Message not sent. Check your connection; the conversation may be unavailable. Please wait before retrying.', 'Mesaj göndərilmədi. Bağlantını yoxla; söhbət əlçatan olmaya bilər. Təkrar cəhddən əvvəl gözlə.', 'Mesaj gönderilmedi. Bağlantını kontrol et; sohbet kullanılamıyor olabilir. Tekrar denemeden önce bekle.'],
    'roomTitle': ['A place for your kind of people.', 'Sənin maraqlarına uyğun bir yer.', 'Senin gibi insanlar için bir yer.'],
    'roomBody': ['Join a community text chat. Voice & video are coming later.', 'İcma mətn söhbətinə qoşul. Səs və video sonrakı mərhələdədir.', 'Topluluk yazılı sohbetine katıl. Ses ve video daha sonra geliyor.'],
    'textRoom': ['TEXT HANGOUT', 'MƏTN OTAĞI', 'YAZILI SOHBET'],
    'joinRoom': ['Join conversation', 'Söhbətə qoşul', 'Sohbete katıl'],
    'emptyRooms': ['New hangouts are on their way.', 'Yeni otaqlar tezliklə gəlir.', 'Yeni odalar yakında.'],
    'you': ['You', 'Sən', 'Sen'],
    'member': ['Member', 'Üzv', 'Üye'],
    'balance': ['Available coins', 'Mövcud coinlər', 'Kullanılabilir coin'],
    'testCoins': ['Test coins · no monetary value', 'Test coinləri · pul dəyəri yoxdur', 'Test coinleri · parasal değeri yok'],
    'shop': ['Coin shop', 'Coin mağazası', 'Coin mağazası'],
    'shopSoon': ['Purchases are not available yet. No payment will be taken.', 'Alış hələ aktiv deyil. Ödəniş tutulmayacaq.', 'Satın alma henüz açık değil. Ödeme alınmayacak.'],
    'soon': ['Coming soon', 'Tezliklə', 'Yakında'],
    'history': ['Recent activity', 'Son əməliyyatlar', 'Son işlemler'],
    'emptyHistory': ['No transactions yet.', 'Hələ əməliyyat yoxdur.', 'Henüz işlem yok.'],
    'giftSent': ['Gift sent!', 'Hədiyyə göndərildi!', 'Hediye gönderildi!'],
    'giftError': ['Gift could not be sent. Check your balance and connection.', 'Hədiyyə göndərilmədi. Balansı və bağlantını yoxla.', 'Hediye gönderilemedi. Bakiyeni ve bağlantını kontrol et.'],
    'rose': ['Rose', 'Qızılgül', 'Gül'],
    'star': ['Star', 'Ulduz', 'Yıldız'],
    'crown': ['Crown', 'Tac', 'Taç'],
    'purchase': ['Coin purchase', 'Coin alışı', 'Coin satın alma'],
    'edit': ['Edit profile', 'Profili dəyiş', 'Profili düzenle'],
    'bio': ['About you', 'Haqqında', 'Hakkında'],
    'interests': ['Interests', 'Maraqlar', 'İlgi alanları'],
    'save': ['Save changes', 'Dəyişiklikləri saxla', 'Değişiklikleri kaydet'],
    'saved': ['Profile updated.', 'Profil yeniləndi.', 'Profil güncellendi.'],
    'logout': ['Sign out', 'Hesabdan çıx', 'Çıkış yap'],
    'exitPreview': ['Exit preview', 'Sınaqdan çıx', 'Ön izlemeden çık'],
    'delete': ['Delete account', 'Hesabı sil', 'Hesabı sil'],
    'deleteBody': ['This permanently deletes your account, profile, messages and wallet. It cannot be undone.', 'Hesabın, profilin, mesajların və cüzdanın həmişəlik silinəcək. Geri qaytarmaq mümkün deyil.', 'Hesabın, profilin, mesajların ve cüzdanın kalıcı olarak silinecek. Bu işlem geri alınamaz.'],
    'noBlocked': ['No blocked accounts.', 'Bloklanmış hesab yoxdur.', 'Engellenen hesap yok.'],
    'gameTitle': ['A little break. A little brainpower.', 'Bir az fasilə. Bir az düşüncə.', 'Biraz mola. Biraz zihin egzersizi.'],
    'gameBody': ['Play World Quiz. Five questions, no coins, just fun.', 'Dünya viktorinasını oyna. Beş sual, coinsiz, sadəcə əyləncə.', 'Dünya testini oyna. Beş soru, coinsiz, sadece eğlence.'],
    'startGame': ['Play World Quiz', 'Viktorinaya başla', 'Teste başla'],
    'next': ['Next question', 'Növbəti sual', 'Sonraki soru'],
    'result': ['See results', 'Nəticələrə bax', 'Sonuçları gör'],
    'again': ['Play again', 'Yenidən oyna', 'Tekrar oyna'],
    'score': ['Your score', 'Nəticən', 'Puanın'],
    'freeGame': ['FREE TO PLAY · NO CASH PRIZES', 'PULSUZ OYUN · PUL MÜKAFATI YOXDUR', 'ÜCRETSİZ OYUN · NAKİT ÖDÜL YOK'],
    'Music': ['Music', 'Musiqi', 'Müzik'],
    'Travel': ['Travel', 'Səyahət', 'Seyahat'],
    'Gaming': ['Gaming', 'Oyun', 'Oyun'],
    'Art': ['Art', 'İncəsənət', 'Sanat'],
    'Sports': ['Sports', 'İdman', 'Spor'],
    'Food': ['Food', 'Yemək', 'Yemek'],
    'missingProfile': ['Your profile could not be loaded. Retry or sign out.', 'Profilin yüklənmədi. Yenidən yoxla və ya hesabdan çıx.', 'Profilin yüklenemedi. Tekrar dene veya çıkış yap.'],
  };
}

