// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZPUVj_wUL59djtE2iLTVNXG9ZRK09ISk',
    appId: '1:719591915896:web:d54dd234b4e12de006888d',
    messagingSenderId: '719591915896',
    projectId: 'vibe-f9d13',
    // Giriş axını tətbiqin öz domenində qalmalıdır.
    // Fərqli domen olsa, Safari yaddaşı bloklayır və Google girişi
    // yarımçıq qalıb istifadəçini geri atır.
    authDomain: 'vibe-f9d13.web.app',
    storageBucket: 'vibe-f9d13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQzBkU4igx0Tib6P4g3o7-gSCbnJqFfTI',
    appId: '1:719591915896:android:ca12702c6b0a2a4606888d',
    messagingSenderId: '719591915896',
    projectId: 'vibe-f9d13',
    storageBucket: 'vibe-f9d13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwpL_xLbD6XOSB-F6pvU4tdlsUcto4SIg',
    appId: '1:719591915896:ios:8eb47f8f33e58e9606888d',
    messagingSenderId: '719591915896',
    projectId: 'vibe-f9d13',
    storageBucket: 'vibe-f9d13.firebasestorage.app',
    iosBundleId: 'az.vibe.app',
  );
}
